kiten.xpm /usr/share/pixmaps/
usr/bin/kiten
usr/bin/kitengen
usr/bin/kitenkanjibrowser
usr/bin/kitenradselect
usr/share/appdata/kiten.appdata.xml
usr/share/applications/org.kde.kiten.desktop
usr/share/applications/org.kde.kitenkanjibrowser.desktop
usr/share/config.kcfg/kiten.kcfg
usr/share/doc/HTML/en/kiten/
usr/share/fonts/kanjistrokeorders/KanjiStrokeOrders.ttf
usr/share/icons/hicolor/*/apps/kiten.*
usr/share/kiten
usr/share/kxmlgui5/kiten/kitenui.rc
usr/share/kxmlgui5/kitenkanjibrowser/kanjibrowserui.rc
usr/share/kxmlgui5/kitenradselect/radselectui.rc
